# Generated by Django 5.2.8 on 2025-11-19 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_inventory_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.store')),
            ],
        ),
    ]
